app_id: c8df0e67-dff2-4ec4-872f-77d976ff8177
app_secret: llMKC497@bqfcuOGIF57{$^
redirect: http://localhost:8000/tutorial/callback
scopes: openid profile offline_access user.read calendars.read Notes.ReadWrite.All
authority: https://login.microsoftonline.com/common
authorize_endpoint: /oauth2/v2.0/authorize
token_endpoint: /oauth2/v2.0/token
